### PR TITLE
Added modal before going to screen Create New Wallet

### PR DESCRIPTION
**Pull request by formaldehid**
screen shot 2018-08-04 at 19 55 24

Regarding to issue 38: https://github.com/nano-wallet-company/nano-wallet-desktop/issues/38

Translations are done with Google Translate so it needs to be checked

### CODE REVIEW

**Comment by kennedybaird** [comment]
I was working on a solution this, but was stuck on best way to check for existing wallet, this is a good simple solution in the interim.

I believe @devinus wants to work towards multi-wallet support soon.

From a UI perspective I would suggest the modal being centered in the screen, by adding `position='center'` to the `bs-modal`

**Comment by formaldehid** [comment]
Thank you for comments @kennedybaird . I saw that you did a lot of contributions before and some are waiting for merge, so I did't want to do something that you did before. It seemed I failed because there is no system for task assignment or something similar.

Regarding centered modal I want to be consistent with logout modal, so I didn't use `position='center'`.

Regarding future work I would like suggest that @devinus would be acting like a team lead and do plan for work, write tasks and then assign those tasks among us, who wants to participate. I would be great also if we could have a short regular meetings, for design and architecture purposes. With this workflow work would be smoother, quicker and most important we won't do something without purpose.

What do you think about organising public contributions in more teamwork? @kennedybaird @devinus

**Comment by kennedybaird** [comment]
Yeah, it's fantastic to have more people doing stuff!

Right, that's cool, I didn't think about that.. to me it made more sense to be in the center for this situation - but that was good thinking from you! :)

Yeah, I agree fully. The work I have been doing recently has been after talking to devinus.

I think it would be great to see a roadmap if possible and tasks, like you suggest, would be a great idea.

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.

**Pull request closed without merging**
